package frame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import frame.HOMECUST;
import frame.Koneksi;
import frame.STOKADMIN;
import java.sql.*;
import java.text.Format;
import javax.swing.*;
import javax.swing.table.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
/**
 *
 * @author ferdy
 */
public class HOMEADMIN extends javax.swing.JFrame {

    /**
     * Creates new form PSHOME
     */
    public HOMEADMIN() {
        initComponents();
        tampil_data();
    }
    
    public void tampil_data(){
    DefaultTableModel tabel=new DefaultTableModel();
    tabel.addColumn("ID");
    tabel.addColumn("Nama Game");
    tabel.addColumn("harga");
    tabel.addColumn("Nama Pembeli");
    tabel.addColumn("Alamat");
    tabel.addColumn("Metode");
    tabel.addColumn("Status");
    
   try  {
        java.sql.Connection conn = (java.sql.Connection)  Koneksi.getKoneksi();
String sql = "select * from penjualan";
java.sql.PreparedStatement pst= conn.prepareStatement ( sql);
ResultSet rs = pst.executeQuery( sql);
      while(rs.next())
        {
        tabel.addRow(new Object[]{
            rs.getString("id"),
            rs.getString("nama_game"),
            rs.getString("harga"),
            rs.getString("nama_pembeli"),
            rs.getString("alamat"),
            rs.getString("metode_pembayaran"),
            rs.getString("status")});
        }
        jTable2.setModel(tabel);
        }
    catch (Exception e){
    }
}

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cd = new javax.swing.JButton();
        cd1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cd2 = new javax.swing.JButton();
        cd3 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tekken 7");
        jPanel4.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Rp 600.000");
        jPanel4.add(jLabel6);

        jButton11.setBackground(new java.awt.Color(0, 55, 145));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Detail");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);

        jTextField6.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 55, 145));

        cd.setBackground(new java.awt.Color(0, 55, 144));
        cd.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd.setForeground(new java.awt.Color(255, 255, 255));
        cd.setText("Kelola Pesanan");
        cd.setActionCommand("CD  Game");
        cd.setBorder(null);
        cd.setBorderPainted(false);
        cd.setContentAreaFilled(false);
        cd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cdMouseClicked(evt);
            }
        });
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        cd1.setBackground(new java.awt.Color(0, 55, 144));
        cd1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd1.setForeground(new java.awt.Color(255, 255, 255));
        cd1.setText("Kelola Pesanan");
        cd1.setActionCommand("CD  Game");
        cd1.setBorder(null);
        cd1.setBorderPainted(false);
        cd1.setContentAreaFilled(false);
        cd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cd1MouseClicked(evt);
            }
        });
        cd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Game", "Harga", "Nama Pembeli", "Alamat", "Metode", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu pembayaran", "Sudah bayar", "Terkirim", "Selesai" }));

        jButton1.setText("Ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cd2.setBackground(new java.awt.Color(0, 55, 144));
        cd2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd2.setForeground(new java.awt.Color(255, 255, 255));
        cd2.setText("Inventaris");
        cd2.setActionCommand("CD  Game");
        cd2.setBorder(null);
        cd2.setBorderPainted(false);
        cd2.setContentAreaFilled(false);
        cd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cd2MouseClicked(evt);
            }
        });
        cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd2ActionPerformed(evt);
            }
        });

        cd3.setBackground(new java.awt.Color(0, 55, 144));
        cd3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd3.setForeground(new java.awt.Color(255, 255, 255));
        cd3.setText("Manajemen User");
        cd3.setActionCommand("CD  Game");
        cd3.setBorder(null);
        cd3.setBorderPainted(false);
        cd3.setContentAreaFilled(false);
        cd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cd3MouseClicked(evt);
            }
        });
        cd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cd)
                        .addGap(302, 302, 302)
                        .addComponent(cd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cd2)
                        .addGap(33, 33, 33)
                        .addComponent(cd3)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cd1)
                            .addComponent(cd3)
                            .addComponent(cd2))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_cdMouseClicked

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cdActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cd1MouseClicked

    private void cd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cd1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int baris = jTable2.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data di tabel terlebih dahulu.");
            return;
        }

        String id = jTable2.getValueAt(baris, 0).toString(); // Asumsi kolom 0 = id
        String statusBaru = cmbStatus.getSelectedItem().toString();

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualanps", "root", "");
            String sql = "UPDATE penjualan SET status=? WHERE id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, statusBaru);
            pst.setString(2, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Status berhasil diubah!");

            tampil_data(); // Refresh tabel
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengubah status.");
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cd2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cd2MouseClicked

    private void cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd2ActionPerformed
STOKADMIN x =new STOKADMIN();
        x.setVisible(true);
        this.dispose();
        x.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_cd2ActionPerformed

    private void cd3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cd3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cd3MouseClicked

    private void cd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd3ActionPerformed
ManajemenUser x =new ManajemenUser();
        x.setVisible(true);
        this.dispose();
        x.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_cd3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOMECUST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOMECUST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOMECUST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOMECUST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOMEADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cd;
    private javax.swing.JButton cd1;
    private javax.swing.JButton cd2;
    private javax.swing.JButton cd3;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
