package frame;

import frame.STOKADMIN;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ferdy
 */
public class ManajemenUser extends javax.swing.JFrame {

    /**
     * Creates new form ManajemenUser
     */
    public ManajemenUser() {
        initComponents();
   this.setLocationRelativeTo(null); // Frame di tengah
        
        // Panggil method untuk mengisi tabel saat frame pertama kali dibuka
        tampilkanData();
    }

    /**
     * Method untuk mengambil data dari service dan menampilkannya di JTable.
     */
    private void tampilkanData() {
        // Tentukan nama-nama kolom untuk tabel Anda
        String[] kolom = {"Nama Lengkap", "Email", "No. Telepon", "Peran"};
        
        // Buat TableModel, ini adalah objek yang mengontrol data di dalam JTable
        DefaultTableModel model = new DefaultTableModel(kolom, 0);
        // 1. Ambil semua data customer dari servi ce
try{
        List<Customer> listCustomer = CustomerService.getInstance().getAllCustomers();

        // 2. Looping melalui setiap customer
        for (Customer customer : listCustomer) {
            // 3. Buat satu baris data untuk tabel
            Object[] dataBaris = {
                customer.getFullname(),
                customer.getEmail(),
                customer.getNomertelpon(), // Pastikan nama getter-nya benar
                customer.getRole()
            };
            // 4. Tambahkan baris tersebut ke model tabel
            model.addRow(dataBaris);
        }
        tabelUser.setModel(model);

        } catch (Exception e) {
   
            JOptionPane.showMessageDialog(this, "Gagal memuat data pengguna: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        cd = new javax.swing.JButton();
        cd1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cd2 = new javax.swing.JButton();
        cd3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 55, 145));

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Email", "Nama Lengkap", "No.Telepon", "Posisi"
            }
        ));
        jScrollPane1.setViewportView(tabelUser);

        cd.setBackground(new java.awt.Color(0, 55, 144));
        cd.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd.setForeground(new java.awt.Color(255, 255, 255));
        cd.setText("Manajemen User");
        cd.setActionCommand("CD  Game");
        cd.setBorder(null);
        cd.setBorderPainted(false);
        cd.setContentAreaFilled(false);
        cd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cdMouseClicked(evt);
            }
        });
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        cd1.setBackground(new java.awt.Color(0, 55, 144));
        cd1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd1.setForeground(new java.awt.Color(255, 255, 255));
        cd1.setText("Kelola Pesanan");
        cd1.setActionCommand("CD  Game");
        cd1.setBorder(null);
        cd1.setBorderPainted(false);
        cd1.setContentAreaFilled(false);
        cd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cd1MouseClicked(evt);
            }
        });
        cd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd1ActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cd2.setBackground(new java.awt.Color(0, 55, 144));
        cd2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd2.setForeground(new java.awt.Color(255, 255, 255));
        cd2.setText("Inventaris");
        cd2.setActionCommand("CD  Game");
        cd2.setBorder(null);
        cd2.setBorderPainted(false);
        cd2.setContentAreaFilled(false);
        cd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cd2MouseClicked(evt);
            }
        });
        cd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd2ActionPerformed(evt);
            }
        });

        cd3.setBackground(new java.awt.Color(0, 55, 144));
        cd3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cd3.setForeground(new java.awt.Color(255, 255, 255));
        cd3.setText("Manajemen User");
        cd3.setActionCommand("CD  Game");
        cd3.setBorder(null);
        cd3.setBorderPainted(false);
        cd3.setContentAreaFilled(false);
        cd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cd3MouseClicked(evt);
            }
        });
        cd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cd3ActionPerformed(evt);
            }
        });

        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cd1)
                .addGap(41, 41, 41)
                .addComponent(cd2)
                .addGap(45, 45, 45)
                .addComponent(cd3)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cd3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    tampilkanData();  
// Memanggil ulang method untuk memuat data terbaru
          
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cdActionPerformed

    private void cdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_cdMouseClicked

    private void cd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd1ActionPerformed
HOMEADMIN x =new HOMEADMIN();
        x.setVisible(true);
        this.dispose();
        x.setLocationRelativeTo(null); 
        // TODO add your handling code here:
    }//GEN-LAST:event_cd1ActionPerformed

    private void cd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cd1MouseClicked

    private void cd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cd2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cd2MouseClicked

    private void cd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd2ActionPerformed
        STOKADMIN x =new STOKADMIN();
        x.setVisible(true);
        this.dispose();
        x.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_cd2ActionPerformed

    private void cd3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cd3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cd3MouseClicked

    private void cd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cd3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 login x =new login();
        x.setVisible(true);
        this.dispose();
        x.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cd;
    private javax.swing.JButton cd1;
    private javax.swing.JButton cd2;
    private javax.swing.JButton cd3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelUser;
    // End of variables declaration//GEN-END:variables
}
