package frame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ferdy
 */
import java.io.File; // Tambahkan ini di bagian paling atas file
import java.io.IOException; // Tambahkan ini di bagian paling atas file
import java.awt.image.BufferedImage; // Tambahkan ini di bagian paling atas file
import javax.imageio.ImageIO; // Tambahkan ini di bagian paling atas file
import javax.swing.JFileChooser; 
import javax.swing.*;
import java.awt.*;

public class StrukFrame extends javax.swing.JFrame {
     private Customer customer; 

   // Konstruktor baru yang akan kita panggil dari fifa1
    public StrukFrame(Customer customer, String namaPembeli, String alamat, String namaGame, String harga, String metodePembayaran) {
        initComponents();
        this.customer = customer; // Panggil metode yang dibuat NetBeans untuk membangun desain
        displayStruk(namaPembeli,alamat,namaGame, harga, metodePembayaran); // Panggil metode kita untuk mengisi data
        setLocationRelativeTo(null); // Agar frame muncul di tengah
    }

    /**
     * Metode untuk mengisi data ke komponen dan membuat QR code.
     */
    private void displayStruk(String namaPembeli, String alamat, String namaGame, String harga, String metodePembayaran) {
        // Mengisi area teks menggunakan nama variabel yang kita atur tadi
        String header = "--------- STRUK PENG STORE ---------\n\n";
        String detailPembelian = String.format(
            "Nama Pembeli      : %s\n" +
            "Alamat Pengiriman : %s\n\n" +
            "----------------------------------------\n" +
            "Deskripsi           Harga\n" +
            "----------------------------------------\n" +
            "%-19s Rp. %s\n\n" +
            "----------------------------------------\n" +
            "Total             : Rp. %s\n" +
            "Metode Pembayaran : %s\n\n",
            namaPembeli, alamat, namaGame, harga, harga, metodePembayaran
        );
        String footer = "--- Terima Kasih Telah Berbelanja! ---\n" +
                        "Silakan lakukan pembayaran dengan memindai QRIS di bawah ini.";

        txtStrukDetails.setText(header + detailPembelian + footer);

        // Membuat dan menampilkan QR Code pada JLabel
        try {
            String qrisText = "ID.CO.GOPAY.QRIS"; 
            int amount = Integer.parseInt(harga.replace(".", ""));
            String qrContent = String.format("000201010212%s%d&pin=false", qrisText, amount);

            com.google.zxing.qrcode.QRCodeWriter qrCodeWriter = new com.google.zxing.qrcode.QRCodeWriter();
            com.google.zxing.common.BitMatrix bitMatrix = qrCodeWriter.encode(qrContent, com.google.zxing.BarcodeFormat.QR_CODE, 200, 200);

            java.awt.image.BufferedImage qrImage = com.google.zxing.client.j2se.MatrixToImageWriter.toBufferedImage(bitMatrix);
            
            // Mengatur ikon pada JLabel menggunakan nama variabel yang kita atur tadi
            lblQRCode.setIcon(new javax.swing.ImageIcon(qrImage));
            lblQRCode.setText(""); // Hapus teks placeholder jika ada

        } catch (com.google.zxing.WriterException | NumberFormatException e) {
            e.printStackTrace();
            lblQRCode.setText("Gagal membuat QR Code");
            lblQRCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStrukDetails = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        lblQRCode = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 55, 145));
        jPanel1.setForeground(new java.awt.Color(0, 55, 145));

        txtStrukDetails.setColumns(20);
        txtStrukDetails.setRows(5);
        jScrollPane1.setViewportView(txtStrukDetails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-exit-48_1.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblQRCode.setBackground(new java.awt.Color(255, 255, 255));
        lblQRCode.setText("qr");

        btnsimpan.setText("simpan ");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnsimpan)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnsimpan)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
new HOMECUST(this.customer).setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
JPanel panelToSave = jPanel2;

    // Buat objek untuk memilih lokasi penyimpanan file
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan Struk Sebagai Gambar");
    // Set nama file default
    fileChooser.setSelectedFile(new File("struk-pembelian.png")); 

    // Tampilkan dialog "Save File"
    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        
        // Pastikan file memiliki ekstensi .png
        if (!fileToSave.getAbsolutePath().endsWith(".png")) {
            fileToSave = new File(fileToSave.getAbsolutePath() + ".png");
        }

        try {
            // Membuat sebuah gambar kosong dengan ukuran yang sama seperti panel
            BufferedImage image = new BufferedImage(panelToSave.getWidth(), panelToSave.getHeight(), BufferedImage.TYPE_INT_RGB);
            
            // "Mengecat" atau "menggambar" isi panel ke gambar yang sudah kita buat
            panelToSave.paint(image.getGraphics());

            // Menyimpan gambar tersebut ke file yang dipilih user dengan format PNG
            ImageIO.write(image, "png", fileToSave);

            // Beri pesan konfirmasi bahwa file berhasil disimpan
            JOptionPane.showMessageDialog(this, "Struk berhasil disimpan sebagai gambar!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            // Tangani jika terjadi error saat penyimpanan
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan struk: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JTextArea txtStrukDetails;
    // End of variables declaration//GEN-END:variables
}
